package:
  name: libgtextutils
  version: 0.7

source:
  fn: libgtextutils-0.7.tar.gz
  url: https://github.com/agordon/libgtextutils/releases/download/0.7/libgtextutils-0.7.tar.gz
  sha1: 92aef0099369d2e57ce47599a5339ca14abfd953

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://github.com/agordon/libgtextutils
  summary: Gordon's Text utils Library
  license: AGPL
  license_file: COPYING
