package:
  name: fastx_toolkit
  version: 0.0.14

source:
  fn: fastx_toolkit-0.0.14.tar.bz2
  url: https://github.com/agordon/fastx_toolkit/releases/download/0.0.14/fastx_toolkit-0.0.14.tar.bz2
  sha1: d8434af2dd647e303506a54ab14fe667aabc1a86

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libgtextutils ==0.7

test:
  commands:
    - "fastx_trimmer -h | grep 'FASTX Toolkit 0.0.14'"

about:
  home: https://github.com/agordon/fastx_toolkit
  summary: FASTA/FASTQ pre-processing programs
  license: AGPL
  license_file: COPYING
