#!/usr/bin/env python
import argparse
import hivmmer

### ARGUMENTS ###
parser = argparse.ArgumentParser(description=hivmmer.__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
parser.add_argument("FASTQ1",
                    help="FASTQ file with forward Illumina reads")
parser.add_argument("FASTQ2",
                    help="FASTQ file with reverse Illumina reads")
parser.add_argument("-t", "--threads",
                    default=1,
                    metavar="N",
                    type=int,
                    help="number of threads")
parser.add_argument("-v", "--version",
                    action="version",
                    version="hivmmer {}".format(hivmmer.__version__))
args = parser.parse_args()

### PIPELINE ###
"""
echo "### STAGE 1: PEAR ###"

pear -y 3G -f "$FQ1" -r "$FQ2" -o ${ID}.pear -k -j $CPU

echo "### STAGE 2: QC FILTERING AND DEDUPE ###"

hivmmer-filter ${ID}.pear.assembled.fastq ${ID}.pear.unassembled.forward.fastq ${ID}.pear.unassembled.reverse.fastq >${ID}.collapsed.fa

echo "### STAGE 3: TRANSLATE ###"

hivmmer-translate $STOPC ${ID}.collapsed.fa >${ID}.collapsed.pfa

echo "### STAGE 4: HMMSEARCH, ROUND 1 ###"

hmmsearch --cpu $CPU --max --notextw -A ${ID}.hmmsearch1.sto -o ${ID}.hmmsearch1.txt "$REF" ${ID}.collapsed.pfa
hmmemit -c "$REF" >${ID}.hmmsearch1.ref.consensus.fa
hmmbuild --cpu $CPU ${ID}.hmmsearch1.hmm ${ID}.hmmsearch1.sto

echo "### STAGE 5: HMMSEARCH, ROUND 2 ###"

hmmsearch --cpu $CPU -E 1000000 --domE 1000000 --max --notextw -A ${ID}.hmmsearch2.sto -o ${ID}.hmmsearch2.txt ${ID}.hmmsearch1.hmm ${ID}.collapsed.pfa
hmmemit -c ${ID}.hmmsearch1.hmm >${ID}.hmmsearch2.ref.consensus.fa
hmmbuild --cpu $CPU ${ID}.hmmsearch2.hmm ${ID}.hmmsearch2.sto

echo "### STAGE 6: CODON TABLE ###"

hivmmer-codons --reads ${ID}.collapsed.fa --hmmer ${ID}.hmmsearch1.txt --ref ${ID}.hmmsearch1.ref.consensus.fa --region $REGION &
hivmmer-codons --reads ${ID}.collapsed.fa --hmmer ${ID}.hmmsearch2.txt --ref ${ID}.hmmsearch2.ref.consensus.fa --region $REGION &
wait

echo "### FINISHED ###"
"""

# vim: expandtab sw=2 ts=2
